-- CREATE DATABASE TABLES & CONFIGURATIONS FOR SEWA OUTDOOR

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Drop existing structures if they exist (clean setup)
drop trigger if exists on_auth_user_created on auth.users;

drop table if exists public.rental_items cascade;
drop table if exists public.rentals cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.profiles cascade;
drop table if exists public.bank_accounts cascade;

drop function if exists public.handle_new_user() cascade;
drop function if exists public.update_updated_at_column() cascade;
drop function if exists public.is_admin() cascade;

drop type if exists rental_status cascade;

-- 3. Create Custom Enum for Rental Status
create type rental_status as enum (
  'pending_payment',      -- Menunggu transfer dari user
  'pending_verification', -- User sudah upload bukti, menunggu verifikasi admin
  'confirmed',            -- Pembayaran disetujui, siap diambil/dikirim
  'rented',               -- Alat sedang dibawa oleh user
  'returned',             -- Alat sudah kembali dengan aman
  'late',                 -- Terlambat mengembalikan
  'cancelled'             -- Pesanan dibatalkan
);

-- 4. Create Tables

-- PROFILES
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  phone text,
  address text,
  role text check (role in ('admin', 'customer')) default 'customer' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CATEGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PRODUCTS
create table public.products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  price_per_day decimal(12, 2) not null check (price_per_day >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  category_id bigint references public.categories(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RENTALS (TRANSAKSI SEWA)
create table public.rentals (
  id uuid default gen_random_uuid() primary key,
  rental_code text not null unique,
  user_id uuid references public.profiles(id) on delete cascade not null,
  start_date date not null,
  end_date date not null,
  total_days integer not null check (total_days > 0),
  total_price decimal(12, 2) not null check (total_price >= 0),
  status rental_status default 'pending_payment' not null,
  bank_name text,
  account_number text,
  account_holder text,
  payment_proof_url text,
  rejection_reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint check_dates check (end_date >= start_date)
);

-- RENTAL ITEMS (DETAIL PRODUK DALAM 1 TRANSAKSI)
create table public.rental_items (
  id uuid default gen_random_uuid() primary key,
  rental_id uuid references public.rentals(id) on delete cascade not null,
  product_id uuid references public.products(id) on delete restrict not null,
  quantity integer not null check (quantity > 0),
  price_per_day decimal(12, 2) not null check (price_per_day >= 0),
  subtotal decimal(12, 2) not null check (subtotal >= 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BANK ACCOUNTS (REKENING TUJUAN TRANSFER ADMIN)
create table public.bank_accounts (
  id bigint generated by default as identity primary key,
  bank_name text not null,
  account_number text not null,
  account_holder text not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Helper Functions & Triggers

-- Function to check if user is admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone, address, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'address',
    coalesce(new.raw_user_meta_data->>'role', 'customer')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Trigger to update updated_at timestamp
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger update_products_updated_at
  before update on public.products
  for each row execute function public.update_updated_at_column();

create trigger update_rentals_updated_at
  before update on public.rentals
  for each row execute function public.update_updated_at_column();


-- 6. Row Level Security (RLS) Policies

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.rentals enable row level security;
alter table public.rental_items enable row level security;
alter table public.bank_accounts enable row level security;

-- PROFILES POLICIES
create policy "Allow users to read their own profile or admin read all"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id or public.is_admin());

create policy "Allow users to update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- CATEGORIES POLICIES (Public read, Admin manage)
create policy "Allow public read categories"
  on public.categories for select
  to public using (true);

create policy "Allow admin to manage categories"
  on public.categories for all
  to authenticated
  using (public.is_admin());

-- PRODUCTS POLICIES (Public read, Admin manage)
create policy "Allow public read products"
  on public.products for select
  to public using (true);

create policy "Allow admin to manage products"
  on public.products for all
  to authenticated
  using (public.is_admin());

-- RENTALS POLICIES
create policy "Allow users to read their own rentals or admin read all"
  on public.rentals for select
  to authenticated
  using (auth.uid() = user_id or public.is_admin());

create policy "Allow users to create rentals"
  on public.rentals for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Allow users to update their own rentals or admin update all"
  on public.rentals for update
  to authenticated
  using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

-- RENTAL ITEMS POLICIES
create policy "Allow users to read their own rental items or admin read all"
  on public.rental_items for select
  to authenticated
  using (
    exists (
      select 1 from public.rentals
      where rentals.id = rental_items.rental_id
      and (rentals.user_id = auth.uid() or public.is_admin())
    )
  );

create policy "Allow users to insert rental items"
  on public.rental_items for insert
  to authenticated
  with check (
    exists (
      select 1 from public.rentals
      where rentals.id = rental_items.rental_id
      and rentals.user_id = auth.uid()
    )
  );

create policy "Allow admin full access to rental items"
  on public.rental_items for all
  to authenticated
  using (public.is_admin());

-- BANK ACCOUNTS POLICIES
create policy "Allow read access to active bank accounts"
  on public.bank_accounts for select
  using (is_active = true or public.is_admin());

create policy "Allow admin full access to bank accounts"
  on public.bank_accounts for all
  to authenticated
  using (public.is_admin());


-- 7. Storage Buckets Setup (product-images & payment-proofs)
insert into storage.buckets (id, name, public)
values 
  ('product-images', 'product-images', true),
  ('payment-proofs', 'payment-proofs', true)
on conflict (id) do update set public = true;

-- Storage RLS Policies
create policy "Public Access to product-images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "Authenticated upload to product-images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'product-images');

create policy "Public Access to payment-proofs"
  on storage.objects for select
  using (bucket_id = 'payment-proofs');

create policy "Authenticated upload to payment-proofs"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'payment-proofs');


-- 8. Insert Dummy Data (Categories & Bank Accounts)
insert into public.categories (name, slug) values 
('Tenda', 'tenda'),
('Tas Carrier', 'tas-carrier'),
('Sepatu Gunung', 'sepatu-gunung'),
('Sleeping Bag & Matras', 'sleeping-bag-matras'),
('Peralatan Masak', 'peralatan-masak'),
('Aksesoris & Lampu', 'aksesoris-lampu');

insert into public.bank_accounts (bank_name, account_number, account_holder) values 
('Bank Central Asia (BCA)', '8410294812', 'PT Sewa Alat Gunung Indonesia'),
('Bank Mandiri', '1370018274615', 'PT Sewa Alat Gunung Indonesia');

-- 9. Insert Dummy Products
insert into public.products (name, description, price_per_day, stock, image_url, category_id) values 
('Tenda Dome Eiger Shaba 4P', 'Tenda kapasitas 4 orang dengan double layer, waterproof, dan frame fiber yang kokoh.', 50000.00, 5, 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?q=80&w=600', (select id from public.categories where slug = 'tenda')),
('Tenda Rei Rinjani 2P', 'Tenda ringan kapasitas 2 orang, cocok untuk ultralight hiking. Tahan badai ringan.', 35000.00, 4, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600', (select id from public.categories where slug = 'tenda')),
('Tas Carrier Deuter Futura Pro 60L', 'Carrier premium Jerman dengan sistem ventilated backsystem yang sangat nyaman di punggung.', 40000.00, 6, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600', (select id from public.categories where slug = 'tas-carrier')),
('Tas Carrier Osprey Atmos 50L', 'Carrier kelas dunia dengan fitur anti-gravity suspension untuk meringankan beban pundak.', 45000.00, 4, 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?q=80&w=600', (select id from public.categories where slug = 'tas-carrier')),
('Sepatu Gunung Consina Alpine', 'Sepatu gunung tahan air dengan sol tebal anti slip dan proteksi mata kaki yang aman.', 25000.00, 8, 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=600', (select id from public.categories where slug = 'sepatu-gunung')),
('Sleeping Bag Eiger Polar Warmth', 'Sleeping bag dengan lapisan thermal fleece polar hangat, menjaga suhu tubuh saat malam dingin.', 12000.00, 15, 'https://images.unsplash.com/photo-1627581177651-41fc408795cd?q=80&w=600', (select id from public.categories where slug = 'sleeping-bag-matras')),
('Kompor Gas Portabel Kovar Windproof', 'Kompor camping mini dengan pelindung angin (windproof tracker), praktis dan hemat gas.', 10000.00, 10, 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?q=80&w=600', (select id from public.categories where slug = 'peralatan-masak')),
('Nesting Cooking Set DS-308', 'Satu set panci wajan camping isi 3 pcs dari bahan aluminium anodized food grade.', 12000.00, 8, 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=600', (select id from public.categories where slug = 'peralatan-masak')),
('Headlamp LED Dimmable Eiger', 'Lampu kepala LED dengan tingkat kecerahan dapat diatur dan baterai rechargeable USB.', 8000.00, 12, 'https://images.unsplash.com/photo-1554734867-bf3c00a49371?q=80&w=600', (select id from public.categories where slug = 'aksesoris-lampu'));
